uploads = []
generated = []

[[outputs]]
id = "Jw_Yt0TgPpQQsxeZD0XfZ"
uri = "file://karaoke-ct-source.tar.gz"
type = "unspecified"
title = "Karaokê CT - Código Fonte (tar.gz)"

[[outputs]]
id = "a1bg81L0ZZ8uCBq0D7SeK"
uri = "file://Karaoke_CT_Documentacao_Completa.pdf"
type = "pdf"
title = "Karaoke CT - Documentação Completa do Código (PDF)"

[[outputs]]
id = "WCViuUHl22TkfcVXkaWHF"
uri = "file://docs/player-comentado.pdf"
type = "pdf"
title = "Documentação Comentada do Player (PDF)"

[[outputs]]
id = "WjCqpCgstKU0LjWDuf_gX"
uri = "file://guides/guia-bunny-stream.pdf"
type = "pdf"
title = "Guia Bunny Stream - Karaoke CT"

[[outputs]]
id = "gUmlbT51sdbvamM2xw2y5"
uri = "file://karaoke_bora_cantar_documentacao_completa.pdf"
type = "pdf"
title = "Karaokê Bora Cantar — Documentação Técnica Completa"

[[outputs]]
id = "ktShGQOSp_bZZA9SJNMkV"
uri = "file://docs/Karaoke-App-Play-Store-Resumo.pdf"
type = "pdf"
title = "Resumo - App Play Store (Primeira Versao)"

[[outputs]]
id = "ZL5cjqWBkC0Wiwtk4Ox3H"
uri = "file://docs/Karaoke-Custos-Play-Store.pdf"
type = "pdf"
title = "Custos Google Play Store"

[[outputs]]
id = "iV7JPrucuQVsMIsK4489K"
uri = "file://docs/Karaoke-Bora-Cantar-App-Play-Store-Completo.pdf"
type = "pdf"
title = "Resumo Completo - App Play Store (Atualizado)"

[[outputs]]
id = "_1_hOFBVbBdMpF1lPhryO"
uri = "file://docs/Karaoke-Bora-Cantar-App-Play-Store-Completo-v2.pdf"
type = "pdf"
title = "Resumo Completo Atualizado (com iPhone e modelo de negocio)"

[[outputs]]
id = "jyTEOUkGf0Fg_vQ8CKtvv"
uri = "file://screenshots/home-with-timer.jpg"
type = "image"
title = "Tela Inicial"

[[outputs]]
id = "qqi4qmlJ4dqc8YRQuUk4A"
uri = "file://screenshots/player-fixed-timer.jpg"
type = "image"
title = "Tela do Player"
